# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GIT_USERNAME: "light-mini"
      GIT_EMAIL: "249068920@qq.com"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # 配置 git
      - name: Set git
        run: |
          sudo apt-get install git
          git config --global user.name "${GIT_USERNAME}"
          git config --global user.email "${GIT_EMAIL}"
      # 下载设备树、内核和厂商文件
      - name: Clone vendor trees
        run: |
          mkdir -p vendor/xiaomi
          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi.git -b lineage-21 vendor/xiaomi
          tar -cf vendor_xiaomi.tar vendor/xiaomi
      # 上传编译结果
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: vendor_xiaomi
          path: vendor_xiaomi.tar
